---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-webui-secret
    template:
      data:
        API_ADMIN_KEY: "{{ .GARAGE_ADMIN_KEY }}"
  dataFrom:
    - extract:
        key: garage-webui
