---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10010
            runAsGroup: 8675309
            fsGroup: 8675309
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0@sha256:37aefd713ba31d51255995261616f1144378887bc5f21665a0ebf851fb85f69a
            env:
              TZ: America/Los_Angeles
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.5.100
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    ingress:
      app:
        className: internal
        hosts:
          - host: qbittorrent.chezlawrence.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      config:
        existingClaim: *app
      media:
        type: nfs
        server: nas0.internal
        path: /tank/downloads/torrents
        globalMounts:
          - path: /data/downloads
      tmpfs:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            app:
              - path: /tmp
                subPath: tmp
