exclude:
  platforms:
  - _info.txt
  - '@eaDir'
  - video
  - .Stfolder
  - images
  - videos
  - '*.Stfolder'
  - '*.txt'
  - '*syncthing*'
  roms:
    multi_file:
      names:
      - _hidden
      - images
      - '@eaDir'
      - '!images'
      - '!orphaned'
      - '!downloading'
      - txt
      - manuals
      - cfg
      - stignore
      - '*videos'
      - '*manuals'
      - .Stfolder
      - '*syncthing*'
      parts:
        extensions:
        - txt
        - xml
        - jpg
        - jpeg
        - images
        - cfg
        - stignore
        - '*videos'
        - .Stfolder
        - '*syncthing*'
        - syncthing
        names:
        - data.xml
        - ._*
        - multidisc
        - manuals
        - cfg
        - '*manuals'
        - syncthing
        - '*syncthing*'
    single_file:
      extensions:
      - xml
      - txt
      - jpg
      - jpeg
      - pdf
      - images
      - manuals
      - '*.cfg'
      - stignore
      - '*.Stfolder'
      - '*syncthing*'
      - syncthing
      names:
      - info.txt
      - ._*
      - '*.nfo'
      - '@eaDir'
      - '*.xml'
      - '!info.txt'
      - mp4
      - '*.mp4'
      - '*.cfg'
      - cfg
      - stignore
      - '*manuals'
      - '*.Stfolder'
      - syncthing
filesystem:
  roms_folder: roms
system:
  platforms:
    3do: 3do
    3ds: 3ds
    adam: colecoadam
    advision: adventure-vision
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacd32: amiga-cd32
    amigacdtv: amiga-cd32
    amstradcpc: acpc
    apfm1000: apf
    apple2: appleii
    apple2gs: apple2gs
    arcadia: arcadia-2001
    archimedes: acorn-archimedes
    arduboy: arduboy
    astrocade: astrocade
    atari2600: atari2600
    atari5200: atari5200
    atari7800: atari7800
    atari800: atari
    atarist: atari-st
    atom: atom
    atomiswave: arcade
    bbcmicro: bbcmicro
    c128: c128
    c20: vic-20
    c64: c64
    camplynx: camputers-lynx
    cdi: philips-cd-i
    channelf: fairchild-channel-f
    coco: trs-80-color-computer
    colecovision: colecovision
    cplus4: c-plus-4
    cps1: cps1
    cps2: cps2
    cps3: cps3
    crvision: creativision
    daphne: daphne
    dos: dos
    dreamcast: dc
    easyrpg: rpgmaker
    fbneo: arcade
    fds: fds
    fm7: fm-7
    fmtowns: fm-towns
    gamate: gamate
    gameandwatch: g-and-w
    gamecom: game-dot-com
    gamecube: ngc
    gamegear: gamegear
    gb: gb
    gb2players: gb
    gba: gba
    gba2players: gba
    gbc: gbc
    gbc2players: gbc
    gp32: gp32
    gzdoom: doom
    intellivision: intellivision
    jaguar: jaguar
    jaguarcd: atari-jaguar-cd
    lcdgames: handheld-electronic-lcd
    lynx: lynx
    mame: arcade
    mastersystem: sms
    megadrive: genesis-slash-megadrive
    megadrive-msu: genesis-slash-megadrive
    megaduck: megaduck
    model2: arcade
    model3: arcade
    msx1: msx
    msx2: msx2
    msx2+: msx2
    n64: n64
    n64dd: 64dd
    naomi: arcade
    naomi2: arcade
    nds: nds
    neogeo: neogeoaes
    neogeocd: neo-geo-cd
    nes: nes
    ngp: neo-geo-pocket
    ngpc: neo-geo-pocket-color
    oricatmos: oric
    pc88: pc-8800-series
    pc98: pc-9800-series
    pcengine: turbografx16--1
    pcenginecd: turbografx-16-slash-pc-engine-cd
    pcfx: pc-fx
    pet: cpet
    pokemini: pokemon-mini
    prboom: doom
    ps2: ps2
    ps3: ps3
    ps4: ps4--1
    psp: psp
    psvita: psvita
    psx: ps
    pv1000: casio-pv-1000
    samcoupe: sam-coupe
    satellaview: satellaview
    saturn: saturn
    scummvm: scummvm
    scv: epoch-super-cassette-vision
    sega32x: sega32
    segacd: segacd
    sg1000: sg1000
    sgb: gbc
    snes: snes
    snes-msu: snes
    spectravideo: spectravideo
    supergrafx: supergrafx
    supervision: supervision
    supracan: super-acan
    switch: switch
    thomson: thomson-mo5
    ti99: ti-99
    tic80: tic
    triforce: arcade
    tutor: tomy-tutor
    vectrex: vectrex
    virtualboy: virtualboy
    vsmile: vsmile
    wii: wii
    wiiu: wiiu
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    x1: x1
    x68000: sharp-x68000
    xbox: xbox
    xbox360: xbox360
    zmachine: z-machine
    zx81: sinclair-zx81
    zxspectrum: zxs
  versions: {}