---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: romm-secret
    template:
      engineVersion: v2
      data:
        # App
        REDIS_HOST: dragonfly.database.svc.cluster.local
        REDIS_PORT: "6379"
        DB_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .ROMM_POSTGRES_USER }}"
        DB_PASSWD: &dbPass "{{ .ROMM_POSTGRES_PASSWORD }}"
        DB_NAME: &dbName romm
        IGDB_CLIENT_ID: "{{ .ROMM_IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .ROMM_IGDB_CLIENT_SECRET }}"
        STEAMGRIDDB_API_KEY: "{{ .ROMM_STEAMGRIDDB_API_KEY }}"
        DISABLE_USERPASS_LOGIN: "false"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: romm
    - extract:
        key: cloudnative-pg
