---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanagerconfig.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard-kubernetes-api-server.yaml
  - ./grafanadashboard-kubernetes-coredns.yaml
  - ./grafanadashboard-kubernetes-global.yaml
  - ./grafanadashboard-kubernetes-namespaces.yaml
  - ./grafanadashboard-kubernetes-nodes.yaml
  - ./grafanadashboard-kubernetes-pods.yaml
  - ./grafanadashboard-kubernetes-volumes.yaml
  - ./grafanadashboard-prometheus.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./scrapeconfig.yaml
