---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  chart:
    spec:
      chart: trivy-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      version: 0.29.0
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 10m0s
  maxHistory: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      annotations:
        reloader.stakater.com/auto: 'true'
      configAuditScannerScanOnlyCurrentRevisions: true
      infraAssessmentScannerEnabled: false
      replicas: 1
      scanJobTTL: 10s
      scanJobsConcurrentLimit: 5
      vulnerabilityScannerScanOnlyCurrentRevisions: true
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
      severity: HIGH,CRITICAL
      slow: true
      storageClassEnabled: false