---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 10m0s
  chart:
    spec:
      chart: trivy-operator
      version: "0.28.1"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      replicas: 1
      scanJobsConcurrentLimit: 5
      scanJobTTL: 10s
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      annotations:
        reloader.stakater.com/auto: "true"
    serviceMonitor:
      enabled: true
    trivy:
      slow: true
      ignoreUnfixed: true
      severity: HIGH,CRITICAL
      storageClassEnabled: false
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
    nodeCollector:
      useNodeSelector: false
