---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    serviceType: LoadBalancer
    service:
      annotations:
        lbipam.cilium.io/ips: "192.168.6.100"
      externalTrafficPolicy: Cluster
    servers:
      - zones:
          - zone: .
            use_tcp: true
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: k8s_gateway
            parameters: "${SECRET_DOMAIN}"
            configBlock: |-
              apex k8s-gateway.network
              ttl 1
              resources Ingress Service HTTPRoute
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: loop
          - name: reload
          - name: loadbalance
