---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./plex/ks.yaml
  - ./pinchflat/ks.yaml
  - ./readarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
