---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /
- search:
    provider: duckduckgo
- openweathermap:
    label: Bothell
    latitude: {{HOMEPAGE_VAR_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_LONGITUDE}}
    units: imperial
    provider: openweathermap
    cache: 5
    format:
      maximumFractionDigits: 1
- datetime:
    text_size: x1
    locale: en
    format:
      timeStyle: short
      hourCycle: h23