---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aliasman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: aliasman-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: aliasman
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .ALIASMAN_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .ALIASMAN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        config.toml: |
          default_system = "default"

          [systems.default]
          domain = "example.com"
          email_addresses = ["me@example.com"]

          [systems.default.storage]
          type = "postgres"
          url = "postgres://{{ .ALIASMAN_POSTGRES_USERNAME }}:{{ .ALIASMAN_POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local/aliasman"

          [systems.default.email]
          type = "rackspace"
          user_key = "{{ .RACKSPACE_USER_KEY }}"
          secret_key = "{{ .RACKSPACE_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: aliasman
    - extract:
        key: cloudnative-pg
