---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-block
