# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:51B9nnhoITaxQ/8338CJc259eHwn3nTlClnlgS75vNo=,iv:CxHhgsl19Rq6BD71YljGTAxxOS7iMHkZvvetQ3z2T+c=,tag:NgSZDLm18kjp8Ke+hocdog==,type:str]
sops:
  age:
    - recipient: age19um8c7z6ckqsddthp6ecprlh69dg66kfwhfs9d6jvq7wze9pj5nqxy5dau
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT2lvUDBYTHJuSTNzSGl3
        ZTE2ZTREREtyRHpTQmVMR3UyUHdycU8yd0NzCmorWDlEdVlvZFlxUUpwNjdMOCtr
        V1dOaWMwWU53YzVHMkxhdDFPSzlIQkUKLS0tIDh4czUzVitsZHJ4elk5NUVtdkRR
        QzFYQkw4Umx4ZWkrTzEvTURDQTFGRlUKh+iVGnBknUlNTuT18kcw3HgUJItNIbHx
        KVXvcmAQYVHNi+G/EXex4+UcxDsFXP5UiXxxGesi0QTfHBQg1zhGpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T00:49:42Z"
  mac: ENC[AES256_GCM,data:jDbXAlFwemHM3tCjys1KDkGdZTW0SS/t/tTSDtRJRZOy+fWu6Yf8Xp6ELRftjjSIRuqayb59+qYHsT7PiZ9t9cE18Ms1bohZkpDqSkMnbmCMUYWpp+CRZ0tpGP8UhLIZPGuE+uwNwX3YSxGu0M85blIoKU+9U8TPC+rdBM3xQT0=,iv:CjDyxLSfY+SyR7MAEHcnxs/TRNalnET/dFHiRSnZcFY=,tag:lMrnJ9CoBJCQaLlcRazP4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
