# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XHGllWP6NoHxjyeqJGRHgbyy64jGUmBvYSHYaOfQQ7U=,iv:E0oVbCmzbbD5pQCQel6RVAY3pXO/Vzpzzhg3S3wjmSo=,tag:L+yqO9Jt7wSFcwLnju0aCQ==,type:str]
sops:
  age:
    - recipient: age19um8c7z6ckqsddthp6ecprlh69dg66kfwhfs9d6jvq7wze9pj5nqxy5dau
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a2ZucFhNeUpYdEsxcjU4
        eHkvdzE5TWtSelZPbVJNa0s5UFFiK2F0Q2tRCjgzaXRKSVFaUi96eWFQa2RmNVdp
        UjZCVzE4di9GbXFyUmsvdVZUcEx5TUUKLS0tIEFUUk84cEYxU0NpTjlEMllFRXdi
        cng2V0Q2ZUtpQ2tEb2VWTHhreGM3S1kK7gZ9J9wMuSOr49fF1aiFeuY73YI0cewF
        5IYVaN3TdBBKwODnwzyVks9eVMxiC/0daur6ly7YqpiI5sZWs4VqIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T22:21:27Z"
  mac: ENC[AES256_GCM,data:WkYi5Xj5BsrDetMuGsdQrOdy3wIfrTgtCchSCdtTB7xzlgGOVaudSIifq/IAwmM914YggHG4cmUk+rK99YsgbNOwljYiiPY9GI++Ji+sKJT3dwFi5rQha4YdllnW7Y8Xg2iBXymSP3Ifm6DfoHh+wsQpJOt6/oOZE1IDcMK5/bc=,iv:w/H05Zp6lULBMNzQ3GtiplIn89lqn8M6b+LhToOHVw8=,tag:7LzpaaCAsQAeEA+Y1XX4/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
