---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secret
    template:
      data:
        # App
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: postgres17-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GF_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .GF_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        admin-user: "{{ .GF_ADMIN_USERNAME }}"
        admin-password: "{{ .GF_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: grafana
