---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
  namespace: llm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: "postgres://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local/open-webui?sslmode=disable"
        # Redis
        # https://docs.openwebui.com/getting-started/advanced-topics/env-configuration/#redis
        ENABLE_WEBSOCKET_SUPPORT: "true"
        WEBSOCKET_MANAGER: "redis"
        WEBSOCKET_REDIS_URL: "redis://dragonfly.databases.svc.cluster.local"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "open-webui"
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .OPENWEBUI_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OPENWEBUI_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: cloudnative-pg
