---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.8.1
  install:
    remediation:
      retries: -1
  interval: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultDataPath: /var/lib/longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 25
      v1DataEngine: true
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${CLUSTER_DOMAIN}
      enabled: true
      host: longhorn.${CLUSTER_DOMAIN}
      ingressClassName: internal
      tls: true
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      defaultClass: false
