---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'

        AUTHENTIK_EMAIL__HOST: smtp-relay.network.svc.cluster.local

        AUTHENTIK_POSTGRESQL__HOST: &dbhost postgres17-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname "authentik"
        AUTHENTIK_POSTGRESQL__USER: &dbuser "{{ .AUTHENTIK_POSTGRES_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass "{{ .AUTHENTIK_POSTGRES_PASSWORD }}"

        AUTHENTIK_STORAGE__MEDIA__BACKEND: "s3"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .AUTHENTIK_AWS_ACCESS_KEY_ID }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .AUTHENTIK_AWS_SECRET_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: authentik-media
        AUTHENTIK_STORAGE__MEDIA__S3__REGION: us-east-1
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: http://minio.storage.svc.cluster.local:9000
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: s3://authentik-media/

        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg