---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: authentik
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
        configmap.reloader.stakater.com/reload: authentik-theme
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: *secret
    blueprints:
      configMaps:
        - authentik-blueprints
    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
        db: 1
    prometheus:
      rules:
        enabled: true
    server:
      replicas: 3
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.4.0@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
          envFrom:
            - secretRef:
                name: *secret
      volumes:
        - name: theme-assets
          configMap:
            name: authentik-theme
      volumeMounts:
        - name: theme-assets
          mountPath: /web/dist/assets/icons/logo-custom.svg
          subPath: logo.svg
          readOnly: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
