---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: authentik-theme
    files:
      - ./resources/logo.png
  - name: authentik-blueprints
    files:
      - ./resources/brand.yaml
generatorOptions:
  disableNameSuffixHash: true
