---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        # App
        READARR__AUTH__APIKEY: "{{ .READARR_API_KEY }}"
        READARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        READARR__POSTGRES__USER: &dbUser "{{ .READARR_POSTGRES_USER }}"
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .READARR_POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_DBNAME: "readarr-main readarr-log readarr-cache"
  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: cloudnative-pg
