---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      data:
        CLUSTER_DOMAIN: "{{ .CLUSTER_DOMAIN }}"
  dataFrom:
    - extract:
        key: cluster-settings
