---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blocky
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: blocky-db-app
    template:
      data:
        # Blocky query log
        DB_URI: "postgres://{{ .BLOCKY_POSTGRES_USER }}:{{ .BLOCKY_POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local/blocky?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: blocky
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .BLOCKY_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .BLOCKY_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: blocky
    - extract:
        key: cloudnative-pg
