---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: blocky
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: blocky
    controllers:
      blocky:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.3.0@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: blocky-db-app
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.26@sha256:b259ada3f943e73283f1fc5e84ac39a791afec7de86515d1aeccc03d2c39e595
            env:
              TZ: America/Los_Angeles
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/blocking/status
                    port: &httpPort 4000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/blocking/status
                    port: *httpPort
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_BIND_SERVICE
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
                  app.kubernetes.io/controller: blocky
      blocky-ui:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/gabeduartem/blocky-ui
              tag: 1.6.1@sha256:35e67a68a6ef15ad43d3b9913ab7e667deaddcb022e414eacc8070a1450b4441
            env:
              QUERY_LOG_TYPE: postgresql
              QUERY_LOG_TARGET:
                secretKeyRef:
                  name: blocky-db-app
                  key: DB_URI
              BLOCKY_API_URL: http://blocky-k8s.network.svc.cluster.local:4000
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: secret
        name: blocky-db-app
        globalMounts:
          - path: /app/config.yml
            subPath: config.yaml
            readOnly: true
    service:
      k8s:
        controller: blocky
        ports:
          http:
            port: *httpPort
      dns:
        controller: blocky
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "192.168.0.100,192.168.0.101,192.168.0.102,192.168.0.103"
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
      ui:
        controller: blocky-ui
        ports:
          http:
            port: 3000
    serviceMonitor:
      app:
        serviceName: blocky-k8s
        endpoints:
          - port: http
