---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        # App
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        RADARR__POSTGRES__USER: &dbUser "{{ .RADARR_POSTGRES_USER }}"
        RADARR__POSTGRES__PASSWORD: &dbPass "{{ .RADARR_POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_DBNAME: "radarr-main radarr-log"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: cloudnative-pg
