---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name manyfold-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # General
        MANYFOLD_SECRET_KEY: "{{ .MANYFOLD_SECRET_KEY }}"
        # Database
        DATABASE_ADAPTER: postgresql
        DATABASE_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        DATABASE_PORT: "5432"
        DATABASE_DB: &dbName manyfold
        DATABASE_USER: &dbUser "{{ .MANYFOLD_POSTGRES_USER }}"
        DATABASE_PASSWORD: &dbPass "{{ .MANYFOLD_POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: manyfold
    - extract:
        key: cloudnative-pg
