upstreams:
  groups:
    default:
      - https://one.one.one.one/dns-query
      - https://dns.quad9.net/dns-query

conditional:
  mapping:
    ${SECRET_DOMAIN}: tcp+udp:192.168.6.100

customDNS:
  mapping:
    brother-printer.internal: 192.168.7.153
    nas0.internal: 192.168.1.0
    nas1.internal: 192.168.1.201
    pve001.internal: 192.168.1.1
    pve002.internal: 192.168.1.2
    pve005.internal: 192.168.1.5

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads
  loading:
    refreshPeriod: 4h

queryLog:
  type: postgresql
  target: $${DB_URI}
  logRetentionDays: 30
  creationAttempts: 3
  creationCooldown: 2s
  flushInterval: 30s

ports:
  dns: 53
  http: 4000

log:
  level: info

prometheus:
  enable: true
  path: /metrics
