---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard-insights.yaml
  - ./grafanadashboard-network-sites.yaml
  - ./grafanadashboard-pdu.yaml
  - ./grafanadashboard-uap.yaml
  - ./grafanadashboard-usw.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
