---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: dockerhub-rate-limit
  namespace: observability
spec:
  matchers:
    - name: alertname
      value: DockerhubRateLimitRisk
