---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pi-hole-dns
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pi-hole-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pi-hole-dns
  install:
    crds: CreateReplace
    disableSchemaValidation: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    disableSchemaValidation: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pi-hole-dns-secret
            key: PIHOLE_PASSWORD
    extraArgs:
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=internal
      - "--pihole-server=https://dns0.${SECRET_DOMAIN}"
    policy: upsert-only
    registry: noop
    sources: ["ingress", "service"]
    txtPrefix: k8s.main.
    txtOwnerId: main
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
