---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.18.0
  install:
    remediation:
      retries: 3
  interval: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    domainFilters:
      - "${SECRET_DOMAIN}"
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            key: *name
            name: &secret external-dns-pihole
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"
      - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
        value: "true"
    extraArgs:
      - "--pihole-server=http://192.168.0.100"
      - "--ignore-ingress-tls-spec"
      - "--ingress-class=internal"
    fullnameOverride: *app
    image:
      repository: gcr.io/k8s-staging-external-dns/external-dns
      tag: v20250402-v0.16.1-48-g1efdf416
    logLevel: debug
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    policy: upsert-only
    provider: pihole
    registry: noop
    serviceMonitor:
      enabled: true
    sources:
      - ingress
      - service
    triggerLoopOnEvent: true
