---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app romm
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: dragonfly-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
    - name: pg-cluster17
      namespace: database
    - name: volsync
      namespace: volsync-system
  prune: true
  interval: 30m
  path: ./kubernetes/apps/default/romm/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_CLAIM: romm
