endpoints:
  - name: "${APP}"
    group: internal
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.chezlawrence.com${GATUS_PATH:=/}"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
