---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.3.2@sha256:4f923bf0e9391b3a8bc5527e539b022e92dcc8a3a13e6ab66122ea9ed030e196
              pullPolicy: IfNotPresent
            env:
              TZ: America/Los_Angeles
              HOMEPAGE_ALLOWED_HOSTS: start.chezlawrence.com
              PORT: &port 3000
            envFrom:
              - secretRef:
                  name: homepage-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
        replicas: 2
        serviceAccount:
          identifier: homepage
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: start.chezlawrence.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /app/configs
      config-files:
        type: configMap
        name: homepage-configmap
        defaultMode: 0775
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
            readOnly: true
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
            readOnly: true
          - path: /app/config/services.yaml
            subPath: services.yaml
            readOnly: true
          - path: /app/config/settings.yaml
            subPath: settings.yaml
            readOnly: true
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
            readOnly: true
          - path: /app/config/docker.yaml
            subPath: docker.yaml
            readOnly: true
          - path: /app/config/custom.css
            subPath: custom.css
            readOnly: true
          - path: /app/config/custom.js
            subPath: custom.js
            readOnly: true
      config-logs:
        type: emptyDir
        enabled: true
        globalMounts:
          - path: /app/config/logs
    serviceAccount:
      homepage: {}
