---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: homepage-configmap
    files:
      - bookmarks.yaml=./resources/bookmarks.yaml
      - kubernetes.yaml=./resources/kubernetes.yaml
      - services.yaml=./resources/services.yaml
      - settings.yaml=./resources/settings.yaml
      - widgets.yaml=./resources/widgets.yaml
      - docker.yaml=./resources/docker.yaml
      - custom.css=./resources/custom.css
      - custom.js=./resources/custom.js
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
