---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-poc-cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wp-cron
              # renovate: datasource=docker depName=curlimages/curl
              image: docker.io/curlimages/curl:8.20.0@sha256:b3f1fb2a51d923260350d21b8654bbc607164a987e2f7c84a0ac199a67df812a
              command: ["curl", "-fsS", "--retry", "3", "--retry-delay", "5", "--retry-all-errors", "http://wordpress-poc.self-hosted.svc.cluster.local/wp-cron.php"]
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  memory: 32Mi
          restartPolicy: Never
