---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-poc-cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wp-cron
              # renovate: datasource=docker depName=curlimages/curl
              image: docker.io/curlimages/curl:8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
              command: ["curl", "-fsS", "--retry", "3", "--retry-delay", "5", "--retry-all-errors", "http://wordpress-poc.self-hosted.svc.cluster.local/wp-cron.php"]
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  memory: 32Mi
          restartPolicy: Never
