---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-etcd-s3-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talos-etcd-s3-keys
    creationPolicy: Owner
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
        RESTIC_REPOSITORY: "{{ .MINIO_URL }}/backups/etcd"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: cluster-settings
    - extract:
        key: minio-backups
