---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-etcd-s3-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talos-etcd-s3-keys
    creationPolicy: Owner
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .ETCD_BACKUP_S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .ETCD_BACKUP_S3_SECRET_ACCESS_KEY }}"
        RESTIC_REPOSITORY: "s3:http://nas0.internal:3900/backups-etcd"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: cluster-settings
    - extract:
        key: etcd-backup
