---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-minio"
    template:
      data:
        RESTIC_REPOSITORY: "{{ .MINIO_URL }}/${APP}"
        RESTIC_PASSWORD: "{{ .VOLSYNC_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: cluster-settings
    - extract:
        key: minio-backups
