---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  restic:
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=longhorn-cache}"
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    moverSecurityContext:
      fsGroup: ${APP_GID:=2000}
      runAsGroup: ${APP_GID:=2000}
      runAsUser: ${APP_UID:=2000}
    pruneIntervalDays: 7
    repository: "${APP}-volsync-minio"
    retain:
      daily: 7
      hourly: 24
    storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-triple}"
    unlock: u1
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=longhorn-snapclass}"
  sourcePVC: "${VOLSYNC_CLAIM:=${APP}}"
  trigger:
    schedule: "0 * * * *"
