---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  restic:
    accessModes:
      - "${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}"
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      runAsUser: ${VOLSYNC_PUID:=1000}
    pruneIntervalDays: 14
    repository: "${APP}-volsync-minio"
    retain:
      daily: 7
      hourly: 24
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 * * * *"
