---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
  name: "${APP}-dst"
spec:
  restic:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=ceph-block}"
    capacity: "${VOLSYNC_CAPACITY:=5Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    enableFileDeletion: true
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      runAsUser: ${VOLSYNC_PUID:=1000}
    repository: "${APP}-volsync-minio"
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
  trigger:
    manual: restore-once
